### ISSUE TITLE
USB Mouse HID for LPC845-BRK?

### ISSUE THREAD

**Issue by brainstorm** [hannobraun/lpc845-example#1]
Hello @hannobraun !

I got one of those LPC845 boards thanks to your introductory course on the last Barcelona Rustfest. Now I'm trying to do something like the following, but in Rust, of course:

https://github.com/LSChyi/blackberry-mini-trackball

I'm using this example repo as a base. I have to say it worked like a charm for debugging and flashing via cargo flash, iterating quickly to get the hall sensors pulse readings from the trackball didn't take more than 10 minutes :tada:

![lpc845_bbtrackball](https://user-images.githubusercontent.com/175587/86534414-a581f080-bf1b-11ea-8f51-26d1c6b25138.jpg)

Now, the next logical step would be to drop some crate in the mix to **quickly have a basic USB HID Mouse** on this board. Ideally this HID could be exposed through the same micro-usb port that the board is connected to, but at this stage I'm not sure it's possible without disturbing cargo flash and others? I don't mind breaking out USB_DM and USB_DP from regular GPIOs if that's what's needed.

I'm thinking on starting to experiment with this crate:

https://crates.io/crates/usbd-hid-device
https://github.com/agalakhov/usbd-hid-device-example

But I'm not sure if there's a better/cleaner/faster way in your opinion? Thanks in advance!

/cc @joshajohnson

**Comment by hannobraun** [comment]
Hey @brainstorm,

I'm glad you're having fun with the board!

> I'm using this example repo as a base. I have to say it worked like a charm for debugging and flashing via cargo flash, iterating quickly to get the hall sensors pulse readings from the trackball didn't take more than 10 minutes :tada:

First off, I would actually recommend you use [`cargo-embed`](https://crates.io/crates/cargo-embed). It's pretty similar to `cargo-flash`: Same authors, same technology, but has a configuration file (no more `--chip=...`) and some more advanced features (RTT for I/O and partial support for a GDB server).

Here's example configuration for the LPC845-BRK: https://github.com/braun-embedded/lpc845-test-stand/blob/master/test-target/Embed.toml (leave out the `serial` part, if you have just one board connected; in fact, I don't think you need any of the `probe` stuff, if there's only one development board).

I created this repository to augment an introductory article that's soon to be published. `cargo-embed` would have meant showing and explaining one more configuration file in the article text, so I chose `cargo-flash` instead.

> Now, the next logical step would be to drop some crate in the mix to **quickly have a basic USB HID Mouse** on this board. Ideally this HID could be exposed through the same micro-usb port that the board is connected to, but at this stage I'm not sure it's possible without disturbing cargo flash and others? I don't mind breaking out USB_DM and USB_DP from regular GPIOs if that's what's needed.

I think the LPC845-BRK is the wrong board for that. It's certainly not possible to do it quickly, if at all. First off, the LPC845 has no USB support. The Micro-USB port is connected to the on-board programmer, and that just connects through to the LPC845's USART to make serial communication possible. I don't think you can use that for HID, at least I wouldn't know how.

Using regular GPIOs could be possible, but then you'd have to implement USB in software or find a library that does that for you. I'm not sure how practical that is. The MCU might not be fast enough to handle USB without hardware support.

I think you're on the right track with [`usbd-hid-device`](https://crates.io/crates/usbd-hid-device) (I also found [`usbd-hid`](https://crates.io/crates/usbd-hid)). I haven't used it, but it's based on [`usb-device`](https://crates.io/crates/usb-device) which I've used together with [`usbd-serial`](https://crates.io/crates/usbd-serial), and it worked great. However, those crates only implement the portable parts of USB. You still need a crate that provides a connection to the specific hardware you're going to use.

I've done all of my own USB work on an STM32L0x2 using [`stm32l0xx-hal`](https://crates.io/crates/stm32l0xx-hal) ([example](https://github.com/stm32-rs/stm32l0xx-hal/blob/master/examples/usb_serial.rs)). As for development boards, I've used the [Catena 4610](https://store.mcci.com/products/mcci-catena-4610-integrated-node-for-lorawan-technology) and [Gnat](https://www.tindie.com/products/TleraCorp/gnat-loragnss-asset-tracker/) (both of which have no on-board programmer), as well as the [STM32L0 Discovery](https://www.st.com/en/evaluation-tools/b-l072z-lrwan1.html) (which was a bit finicky with OpenOCD; might or might not work better with cargo-embed). Not sure what to recommend. There are probably better boards out there for your use case.

Whatever you end up doing, it might be asking for recommendations in the [rust-embedded Matrix channel](https://matrix.to/#/#rust-embedded:matrix.org).

**Comment by brainstorm** [comment]
Woah, thanks for the comprehensive response!

That's what I suspected after looking the datasheet a bit more closely. Since I'm not up to writing a bitbanged software USB stack for that board in Rust (at the moment), I think I'll just go and connect [a cheap HID BLE module I have on my project boxes](http://www.edatop.com/down/hwrf/wifibt/BT-WiFi-52rf5528.pdf) to one of the LPC845 UART ports as a workaround for now ;)

I had `cargo-embed` on my radar as well, I was just used cargo flash from before (working with a nordic IC).

Cheers and thanks a ton for all the pointers and insight!
